"""Add payment_gateways table

Revision ID: 1ae9abe1b276
Revises: bc616f1a1b43
Create Date: 2025-09-02 22:22:58.674536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae9abe1b276'
down_revision: Union[str, Sequence[str], None] = 'bc616f1a1b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_gateways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gateway_type', sa.Enum('TON_WALLET', 'STRIPE', 'PADDLE', name='gatewaytype'), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_payment_gateways_id'), 'payment_gateways', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_gateways_id'), table_name='payment_gateways')
    op.drop_table('payment_gateways')
    # ### end Alembic commands ###
